apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: output-secret-config-string
spec:
  encryptedData:
    connection-string: AgBk13vaMQjrxYu1p9i3jNcmcYIJSSB9DgIrQWi2b2R8WY55W2oIKzuuBmfvDCOxa83g+VDufcsm7H8uNtZGFgYrbFFULo+SHQa7q+0llyX76jGqxt85ReyNUT+eWMrIFG2QNEmeZb1hhQRmyJ5NjCzdVqlm3xAFgyesf8LtlkuIbf8irOF7aFvQxbrL1AjHEqREaNs6OHruzfxBXnKlE997LKCo+VxyK+a9DOXMDvIspxaO2448O+tS42c4V5XKeyeZfCdLTigL9ntxin3fvD5gcB+c+ddaLWMLrqd+sG2aVIsbvlQUdYTgghTbruXLKz66GyaC/Q33YM0a2DAzGKTpiMMEA5aNfCyZkCM7nkb94rnB0iZqSjvekdodT3hSGjMmEaWIk56o0BwIpxUn5e6S7szafcXTlVTRFeojxYywE3fusqjIHbZT7f8A8+aAvBYp9594TpRs6Toi28IYSPPHB2W1qq3i439YHmPU7S8PDIGDeHTwNX48OB/YwC3+FoCsF7mLV65RT1NO9WRdBMOFe/XuscrhL1LkSUY8p0UoZD8MhF5TG1iliaFedJ4wtLGpeTR3KZzRS4Qn6T7yS+A0Gr6HxsldkVhenRQ5dHUW1i7SaCVaTIy7n3cxefpiz9oIQUfQNQ1fF7O2Sok7URDwX0LI0a1NRyU0KvDXo4PMVVDKXPuncTsfvX4tafBN2vCUnyb6EkzRjWMh7dgq4Hh6uvTl57QNKzRGfKc=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: output-secret-config-string

